server:
  port: 8000
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433; DatabaseName=mdm_crm
    username: sa
    password: root
